branches:
  except:
    - gh_pages
environment:
  matrix:
    - TARGET: i686-pc-windows-gnu
      BITS: 32
    - TARGET: x86_64-pc-windows-gnu
      BITS: 64
install:
  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-toolchain=nightly-%TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build
  - cargo test

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
